### ISSUE TITLE
Make the site a one page scroll down

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/ifrcgo_v2#13]

**Comment by dalekunce** [comment]
do you mean that you want all of the labs stuff on a single page?

**Comment by guipizzini** [comment]
Its fine the way it looks now. But would need to have the header fixed so that when you scroll down you can still navigate the site. Makes sense?

**Comment by dalekunce** [comment]
you want the header to float on the top as you scroll down, I don't think that is needed, but doable.
