### ISSUE TITLE
Change HXL beta links to hxl proxy production

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/ifrcgo_v2#15]

**Comment by dalekunce** [comment]
@SimonbJohnson can I just remove beta from the proxy uri?

**Comment by Zibethin** [comment]
We tried with Simon but I think he is using a feature which is only on the beta at the moment

**Comment by SimonbJohnson** [comment]
You can remove .beta from all links, except those which have a get parameter verify in them.  That is only used in the field report calls.  All others are good to remove.

**Comment by dalekunce** [comment]
done a80b019
