### ISSUE TITLE
about page

### ISSUE THREAD

**Issue by dalekunce** [IFRCGo/ifrcgo_v2#25]
make an about page with all the NS logos of those that have help out.

@guipizzini @renecnielsen please add all the NS to this list.

- BritCross
- AmCross
- JapaneseRC
- NetherlandsRC

**Comment by renecnielsen** [comment]
The list is now complete. Let's make it explicit that it's NSs who have contributed personnel and funding.

**Comment by dalekunce** [comment]
@renecnielsen can you provide a paragraph on *what* GO is and the language around the $ vs 👨‍🍳

**Comment by renecnielsen** [comment]
I'll close this for now but it might need some styling at some point.
