### ISSUE TITLE
p tag default is centred

### ISSUE THREAD

**Issue by SimonbJohnson** [IFRCGo/ifrcgo_v2#28]
Can we change this to left aligned as I think that is the common use case?

Is it only the landing page that has some centre aligned?

@dalekunce @guipizzini

**Comment by SimonbJohnson** [comment]
<img width="862" alt="screen shot 2017-03-09 at 17 02 48" src="https://cloud.githubusercontent.com/assets/2110742/23761320/56a1d28a-04ea-11e7-9337-a19b23e84c67.png">

Default p also has margin's on which means it doesn't align align.  Will remove both soon, if no objects.

**Comment by renecnielsen** [comment]
The p text-align: center; is in _site.scss which is called by main.scss which in turn is called by the header, which is in all pages built with the default layout. I agree that we should change that.

So I did.

I also removed the centering of headers and use the class `text-center` where needed instead.

+ a lot of other styling tha'll likely break some stuff.
