### ISSUE TITLE
Appeals site to run off one spreadsheet

### ISSUE THREAD

**Issue by SimonbJohnson** [IFRCGo/ifrcgo_v2#46]
Currently two spreadsheets need to be maintained.  Original one for AJAX calls and new one for Jekyll build.

**Comment by dalekunce** [comment]
@SimonbJohnson this is the last thing for launch. Chance you can do it today?

**Comment by SimonbJohnson** [comment]
70dc757a23e9abe3cff0e0d76baf814d97b7ba76
