### ISSUE TITLE
3W map data

### ISSUE THREAD

**Issue by dalekunce** [IFRCGo/ifrcgo_v2#5]
The 3w is not working as the assets are pointing the wrong location, relative to the page rather than the root:
http://ifrcgo.org/ifrcgo_v2/global3w/assets/map/worldmap.json
rather than
http://ifrcgo.org/ifrcgo_v2/assets/map/worldmap.json

@SimonbJohnson

**Comment by dalekunce** [comment]
@SimonbJohnson I can't make sense of the geom call, its not like any of the others. Can you fix this please.

**Comment by SimonbJohnson** [comment]
@dalekunce dev is behind publish, which branch do you want me to develop on and make a pull request against.

**Comment by dalekunce** [comment]
dev is up to date with publish. @SimonbJohnson :)

**Comment by SimonbJohnson** [comment]
@dalekunce fixed here https://github.com/IFRCGo/ifrcgo_v2/pull/7/commits/3bf826c120fa513b3303004766949b1ad598d85f 

Would it be better to have the variable only available in specific pages?  I'm guessing the templating variable is not available in .js files, but would it be more appropriate to move them to the individual html pages?

**Comment by dalekunce** [comment]
I'm confused what you are saying about a variable? Variable for what?
